### ISSUE TITLE
Ask for help to getting  data in json

### ISSUE THREAD

**Issue by Olive80** [oxinon/BTC-price-ticker-V2_1-TTGO-T-Display#1]
Hi,
First of all thank you for sharing your project.
I open a problem because I have this error message on Arduino serial monitor and I have a black screen on my ttgo. 

![Capture1](https://user-images.githubusercontent.com/58820544/146910875-94b09ca8-710e-4fe8-ba79-7a1f07799e84.PNG)

Can you help me because I can't solve it. 
Thank you
Oliver

**Comment by Olive80** [comment]
hi,
I solve the problem of the black screen
but i sill get this error message...
![Capture1](https://user-images.githubusercontent.com/58820544/147049298-e1b1871d-bd6a-442f-a3e0-22da76db8659.PNG)
waiting for your response
Best regard

**Comment by oxinon** [comment]
Hi Olive80,

do you have esptool installed? This makes it possible to delete the memory and then simply transfer it again with the Arduino IDE.

**Comment by Olive80** [comment]
Hello,

I erased the memory with esptool, but without success, always the same error code ... Do you have another solution?

**Comment by oxinon** [comment]
I found the problem, it's with the Coinmarketcap library. Open this file with Notepad++ or another editor /Arduino/libraries/CoinMarketCapApi2/scr/CoinMarketCapApi.ccp

go to line 76 and change the setting from 2048 to 3072
DynamicJsonDocument doc (3072);

Then save, recompile and flash.

**Comment by Olive80** [comment]
Great
It's working perfectly !!!
Thank again for your help and your nice project 
Best regard

**Comment by oxinon** [comment]
No problem, then I can close it here. And merry christmas :)
